// <auto-generated />
using System;
using CareerMate.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CareerMate.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20240802074835_DailyDiaryApprovalStatusChanges3")]
    partial class DailyDiaryApprovalStatusChanges3
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CareerMate.Models.Entities.Applicants.Applicant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("InternshipPostId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("StudentId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("InternshipPostId");

                    b.HasIndex("StudentId");

                    b.ToTable("Applicant", (string)null);
                });

            modelBuilder.Entity("CareerMate.Models.Entities.ApplicationUsers.ApplicationUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("FirstName")
                        .HasColumnType("text");

                    b.Property<string>("LastName")
                        .HasColumnType("text");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("CareerMate.Models.Entities.ApplicationUsers.ApplicationUserRoles", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("CareerMate.Models.Entities.Certifications.Certification", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateOnly>("IssuedMonth")
                        .HasColumnType("date");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Organization")
                        .HasColumnType("text");

                    b.Property<Guid?>("StudentId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("StudentId");

                    b.ToTable("Certification", (string)null);
                });

            modelBuilder.Entity("CareerMate.Models.Entities.Companies.Company", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Address")
                        .HasColumnType("text");

                    b.Property<Guid>("ApplicationUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("Bio")
                        .HasColumnType("text");

                    b.Property<int?>("CompanySize")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<Guid>("FacultyId")
                        .HasColumnType("uuid");

                    b.Property<string>("FirebaseLogoId")
                        .HasColumnType("text");

                    b.Property<DateOnly?>("FoundedOn")
                        .HasColumnType("date");

                    b.Property<Guid>("IndustryId")
                        .HasColumnType("uuid");

                    b.Property<string>("Location")
                        .HasColumnType("text");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<int?>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("WebURL")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationUserId")
                        .IsUnique();

                    b.HasIndex("FacultyId");

                    b.HasIndex("IndustryId");

                    b.ToTable("Company", (string)null);
                });

            modelBuilder.Entity("CareerMate.Models.Entities.CompanyFollowers.CompanyFollower", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("StudentId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.HasIndex("StudentId");

                    b.ToTable("CompanyFollower", (string)null);
                });

            modelBuilder.Entity("CareerMate.Models.Entities.CompanyLeaveRequests.CompanyLeaveRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Approved")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Reason")
                        .HasColumnType("text");

                    b.Property<Guid?>("StudentId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("StudentId");

                    b.ToTable("CompanyLeaveRequest", (string)null);
                });

            modelBuilder.Entity("CareerMate.Models.Entities.CoordinatorAssistants.CoordinatorAssistant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ApplicationUserId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("FacultyId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationUserId")
                        .IsUnique();

                    b.HasIndex("FacultyId");

                    b.ToTable("CoordinatorAssistant", (string)null);
                });

            modelBuilder.Entity("CareerMate.Models.Entities.Coordinators.Coordinator", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ApplicationUserId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("FacultyId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationUserId")
                        .IsUnique();

                    b.HasIndex("FacultyId");

                    b.ToTable("Coordinator", (string)null);
                });

            modelBuilder.Entity("CareerMate.Models.Entities.DailyDiaries.DailyDiary", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("InternId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsLocked")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("StudentId")
                        .HasColumnType("uuid");

                    b.Property<string>("Summary")
                        .HasColumnType("text");

                    b.Property<string>("TrainingLocation")
                        .HasColumnType("text");

                    b.Property<int>("Week")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("InternId");

                    b.HasIndex("StudentId");

                    b.ToTable("DailyDiary", (string)null);
                });

            modelBuilder.Entity("CareerMate.Models.Entities.DailyRecords.DailyRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<int>("Day")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<Guid>("DiaryId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("DiaryId");

                    b.ToTable("DailyRecord", (string)null);
                });

            modelBuilder.Entity("CareerMate.Models.Entities.Degrees.Degree", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Acronym")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("FacultyId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("FacultyId");

                    b.ToTable("Degree", (string)null);
                });

            modelBuilder.Entity("CareerMate.Models.Entities.Experiences.Experience", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CompanyName")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("EmploymentType")
                        .HasColumnType("integer");

                    b.Property<DateOnly>("From")
                        .HasColumnType("date");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("StudentId")
                        .HasColumnType("uuid");

                    b.Property<string>("Title")
                        .HasColumnType("text");

                    b.Property<DateOnly>("To")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.HasIndex("StudentId");

                    b.ToTable("Experience", (string)null);
                });

            modelBuilder.Entity("CareerMate.Models.Entities.Faculties.Faculty", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ShortName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("UniversityId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UniversityId");

                    b.ToTable("Faculty", (string)null);
                });

            modelBuilder.Entity("CareerMate.Models.Entities.Industries.Industry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("FacultyId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("FacultyId");

                    b.ToTable("Industry", (string)null);
                });

            modelBuilder.Entity("CareerMate.Models.Entities.Interns.Intern", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("CompanyId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateOnly>("EndedDate")
                        .HasColumnType("date");

                    b.Property<Guid>("InternshipId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("IsDeletedAt")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateOnly>("StartedDate")
                        .HasColumnType("date");

                    b.Property<Guid>("StudentId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("SupervisorId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.HasIndex("InternshipId");

                    b.HasIndex("StudentId")
                        .IsUnique();

                    b.HasIndex("SupervisorId");

                    b.ToTable("Intern", (string)null);
                });

            modelBuilder.Entity("CareerMate.Models.Entities.InternshipInvites.InternshipInvite", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("InternshipId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("StudentId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("InternshipId");

                    b.HasIndex("StudentId");

                    b.ToTable("InternshipInvite", (string)null);
                });

            modelBuilder.Entity("CareerMate.Models.Entities.InternshipPosts.InternshipPost", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("CompanyId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedUserRole")
                        .HasColumnType("text");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<Guid>("FacultyId")
                        .HasColumnType("uuid");

                    b.Property<string>("FlyerUrl")
                        .HasColumnType("text");

                    b.Property<Guid>("InternshipId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsApproved")
                        .HasColumnType("boolean");

                    b.Property<string>("Location")
                        .HasColumnType("text");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("NumberOfPositions")
                        .HasColumnType("integer");

                    b.Property<Guid?>("PostedCoordinatorAssistantId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("PostedCoordinatorId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("PostedStudentId")
                        .HasColumnType("uuid");

                    b.Property<string>("Title")
                        .HasColumnType("text");

                    b.Property<int>("WorkPlaceType")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.HasIndex("FacultyId");

                    b.HasIndex("InternshipId")
                        .IsUnique();

                    b.HasIndex("PostedCoordinatorAssistantId");

                    b.HasIndex("PostedCoordinatorId");

                    b.HasIndex("PostedStudentId");

                    b.ToTable("InternshipPost", (string)null);
                });

            modelBuilder.Entity("CareerMate.Models.Entities.Internships.Internship", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<Guid>("FacultyId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Title")
                        .HasColumnType("text");

                    b.Property<int>("WorkPlaceType")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.HasIndex("FacultyId");

                    b.ToTable("Internship", (string)null);
                });

            modelBuilder.Entity("CareerMate.Models.Entities.Links.Contact", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("CompanyId")
                        .HasColumnType("uuid");

                    b.Property<int>("ContactType")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Data")
                        .HasColumnType("text");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("StudentId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.HasIndex("StudentId");

                    b.ToTable("Contact", (string)null);
                });

            modelBuilder.Entity("CareerMate.Models.Entities.Pathways.Pathway", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("DegreeId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("DegreeId");

                    b.ToTable("Pathway", (string)null);
                });

            modelBuilder.Entity("CareerMate.Models.Entities.Skills.Skill", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("CompanyId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<Guid?>("StudentId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.HasIndex("StudentId");

                    b.ToTable("Skill", (string)null);
                });

            modelBuilder.Entity("CareerMate.Models.Entities.StudentBatches.StudentBatch", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("BatchCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateOnly>("BatchEndAt")
                        .HasColumnType("date");

                    b.Property<DateOnly>("BatchStartAt")
                        .HasColumnType("date");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("DailyDiaryDueWeeks")
                        .HasColumnType("integer");

                    b.Property<Guid>("FacultyId")
                        .HasColumnType("uuid");

                    b.Property<DateOnly>("LastAllowedDateForStartInternship")
                        .HasColumnType("date");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("ValidInternshipPeriodInMonths")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("FacultyId");

                    b.ToTable("StudentBatch", (string)null);
                });

            modelBuilder.Entity("CareerMate.Models.Entities.Students.Student", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("About")
                        .HasColumnType("text");

                    b.Property<Guid?>("ApplicationUserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("BatchId")
                        .HasColumnType("uuid");

                    b.Property<float?>("CGPA")
                        .HasColumnType("real");

                    b.Property<byte[]>("CV")
                        .HasColumnType("bytea");

                    b.Property<int>("CVStatus")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CvName")
                        .HasColumnType("text");

                    b.Property<Guid?>("DegreeId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FirstName")
                        .HasColumnType("text");

                    b.Property<string>("Headline")
                        .HasColumnType("text");

                    b.Property<string>("LastName")
                        .HasColumnType("text");

                    b.Property<string>("Location")
                        .HasColumnType("text");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("PathwayId")
                        .HasColumnType("uuid");

                    b.Property<string>("PersonalEmail")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<string>("ProfilePicFirebaseId")
                        .HasColumnType("text");

                    b.Property<int?>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("StudentId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UniversityEmail")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationUserId")
                        .IsUnique();

                    b.HasIndex("BatchId");

                    b.HasIndex("DegreeId");

                    b.HasIndex("PathwayId");

                    b.ToTable("Student", (string)null);
                });

            modelBuilder.Entity("CareerMate.Models.Entities.Supervisors.Supervisor", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ApplicationUserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Designation")
                        .HasColumnType("text");

                    b.Property<string>("FirstName")
                        .HasColumnType("text");

                    b.Property<string>("LastName")
                        .HasColumnType("text");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationUserId")
                        .IsUnique();

                    b.HasIndex("CompanyId");

                    b.ToTable("Supervisor", (string)null);
                });

            modelBuilder.Entity("CareerMate.Models.Entities.SysAdmins.SysAdmin", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ApplicationUserId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationUserId")
                        .IsUnique();

                    b.ToTable("SysAdmin", (string)null);
                });

            modelBuilder.Entity("CareerMate.Models.Entities.Universities.University", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ShortName")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("University", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("CareerMate.Models.Entities.Applicants.Applicant", b =>
                {
                    b.HasOne("CareerMate.Models.Entities.InternshipPosts.InternshipPost", "InternshipPost")
                        .WithMany("Applicants")
                        .HasForeignKey("InternshipPostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CareerMate.Models.Entities.Students.Student", "Student")
                        .WithMany("Applicants")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("InternshipPost");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("CareerMate.Models.Entities.Certifications.Certification", b =>
                {
                    b.HasOne("CareerMate.Models.Entities.Students.Student", "Student")
                        .WithMany("Certification")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Student");
                });

            modelBuilder.Entity("CareerMate.Models.Entities.Companies.Company", b =>
                {
                    b.HasOne("CareerMate.Models.Entities.ApplicationUsers.ApplicationUser", "ApplicationUser")
                        .WithOne("Company")
                        .HasForeignKey("CareerMate.Models.Entities.Companies.Company", "ApplicationUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CareerMate.Models.Entities.Faculties.Faculty", "Faculty")
                        .WithMany("Companies")
                        .HasForeignKey("FacultyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CareerMate.Models.Entities.Industries.Industry", "Industry")
                        .WithMany("Companies")
                        .HasForeignKey("IndustryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("CareerMate.Models.Entities.Companies.CompanyRating", "Ratings", b1 =>
                        {
                            b1.Property<Guid>("CompanyId")
                                .HasColumnType("uuid");

                            b1.Property<int?>("TotalRaters")
                                .HasColumnType("integer")
                                .HasColumnName("TotalRaters");

                            b1.Property<decimal?>("TotalRatings")
                                .HasColumnType("numeric")
                                .HasColumnName("TotalRatings");

                            b1.HasKey("CompanyId");

                            b1.ToTable("Company");

                            b1.WithOwner()
                                .HasForeignKey("CompanyId");
                        });

                    b.Navigation("ApplicationUser");

                    b.Navigation("Faculty");

                    b.Navigation("Industry");

                    b.Navigation("Ratings");
                });

            modelBuilder.Entity("CareerMate.Models.Entities.CompanyFollowers.CompanyFollower", b =>
                {
                    b.HasOne("CareerMate.Models.Entities.Companies.Company", "Company")
                        .WithMany("Followers")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CareerMate.Models.Entities.Students.Student", "Student")
                        .WithMany("CompanyFollowers")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Company");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("CareerMate.Models.Entities.CompanyLeaveRequests.CompanyLeaveRequest", b =>
                {
                    b.HasOne("CareerMate.Models.Entities.Students.Student", "Student")
                        .WithMany("LeaveRequests")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Student");
                });

            modelBuilder.Entity("CareerMate.Models.Entities.CoordinatorAssistants.CoordinatorAssistant", b =>
                {
                    b.HasOne("CareerMate.Models.Entities.ApplicationUsers.ApplicationUser", "ApplicationUser")
                        .WithOne("CoordinatorAssistant")
                        .HasForeignKey("CareerMate.Models.Entities.CoordinatorAssistants.CoordinatorAssistant", "ApplicationUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CareerMate.Models.Entities.Faculties.Faculty", "Faculty")
                        .WithMany("CoordinatorsAssistants")
                        .HasForeignKey("FacultyId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("ApplicationUser");

                    b.Navigation("Faculty");
                });

            modelBuilder.Entity("CareerMate.Models.Entities.Coordinators.Coordinator", b =>
                {
                    b.HasOne("CareerMate.Models.Entities.ApplicationUsers.ApplicationUser", "ApplicationUser")
                        .WithOne("Coordinator")
                        .HasForeignKey("CareerMate.Models.Entities.Coordinators.Coordinator", "ApplicationUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CareerMate.Models.Entities.Faculties.Faculty", "Faculty")
                        .WithMany("Coordinators")
                        .HasForeignKey("FacultyId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("ApplicationUser");

                    b.Navigation("Faculty");
                });

            modelBuilder.Entity("CareerMate.Models.Entities.DailyDiaries.DailyDiary", b =>
                {
                    b.HasOne("CareerMate.Models.Entities.Interns.Intern", "Intern")
                        .WithMany("Diary")
                        .HasForeignKey("InternId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("CareerMate.Models.Entities.Students.Student", null)
                        .WithMany("Diary")
                        .HasForeignKey("StudentId");

                    b.OwnsOne("CareerMate.Models.Entities.DailyDiaries.CoordinatorApproval", "CoordinatorApproval", b1 =>
                        {
                            b1.Property<Guid>("DailyDiaryId")
                                .HasColumnType("uuid");

                            b1.Property<DateTime?>("RequestedApprovalAt")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("RequestedCoordinatorApprovalAt");

                            b1.Property<int>("Status")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer")
                                .HasDefaultValue(0)
                                .HasColumnName("CoordinatorApprovalStatus");

                            b1.HasKey("DailyDiaryId");

                            b1.ToTable("DailyDiary");

                            b1.WithOwner()
                                .HasForeignKey("DailyDiaryId");
                        });

                    b.OwnsOne("CareerMate.Models.Entities.DailyDiaries.InternshipPeriod", "InternshipPeriod", b1 =>
                        {
                            b1.Property<Guid>("DailyDiaryId")
                                .HasColumnType("uuid");

                            b1.Property<DateOnly>("From")
                                .HasColumnType("date")
                                .HasColumnName("InternshipPeriodFrom");

                            b1.Property<DateOnly>("To")
                                .HasColumnType("date")
                                .HasColumnName("InternshipPeriodTo");

                            b1.HasKey("DailyDiaryId");

                            b1.ToTable("DailyDiary");

                            b1.WithOwner()
                                .HasForeignKey("DailyDiaryId");
                        });

                    b.OwnsOne("CareerMate.Models.Entities.DailyDiaries.PeriodCovered", "PeriodCovered", b1 =>
                        {
                            b1.Property<Guid>("DailyDiaryId")
                                .HasColumnType("uuid");

                            b1.Property<DateOnly>("From")
                                .HasColumnType("date")
                                .HasColumnName("PeriodCoveredFrom");

                            b1.Property<DateOnly>("To")
                                .HasColumnType("date")
                                .HasColumnName("PeriodCoveredTo");

                            b1.HasKey("DailyDiaryId");

                            b1.ToTable("DailyDiary");

                            b1.WithOwner()
                                .HasForeignKey("DailyDiaryId");
                        });

                    b.OwnsOne("CareerMate.Models.Entities.DailyDiaries.SupervisorApproval", "SupervisorApproval", b1 =>
                        {
                            b1.Property<Guid>("DailyDiaryId")
                                .HasColumnType("uuid");

                            b1.Property<DateTime?>("RequestedApprovalAt")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("RequestedSupervisorApprovalAt");

                            b1.Property<int>("Status")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer")
                                .HasDefaultValue(0)
                                .HasColumnName("SupervisorApprovalStatus");

                            b1.HasKey("DailyDiaryId");

                            b1.ToTable("DailyDiary");

                            b1.WithOwner()
                                .HasForeignKey("DailyDiaryId");
                        });

                    b.Navigation("CoordinatorApproval")
                        .IsRequired();

                    b.Navigation("Intern");

                    b.Navigation("InternshipPeriod")
                        .IsRequired();

                    b.Navigation("PeriodCovered")
                        .IsRequired();

                    b.Navigation("SupervisorApproval");
                });

            modelBuilder.Entity("CareerMate.Models.Entities.DailyRecords.DailyRecord", b =>
                {
                    b.HasOne("CareerMate.Models.Entities.DailyDiaries.DailyDiary", "Diary")
                        .WithMany("Records")
                        .HasForeignKey("DiaryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Diary");
                });

            modelBuilder.Entity("CareerMate.Models.Entities.Degrees.Degree", b =>
                {
                    b.HasOne("CareerMate.Models.Entities.Faculties.Faculty", "Faculty")
                        .WithMany("Degrees")
                        .HasForeignKey("FacultyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Faculty");
                });

            modelBuilder.Entity("CareerMate.Models.Entities.Experiences.Experience", b =>
                {
                    b.HasOne("CareerMate.Models.Entities.Students.Student", "Student")
                        .WithMany("Experiences")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Student");
                });

            modelBuilder.Entity("CareerMate.Models.Entities.Faculties.Faculty", b =>
                {
                    b.HasOne("CareerMate.Models.Entities.Universities.University", "University")
                        .WithMany("Faculties")
                        .HasForeignKey("UniversityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("University");
                });

            modelBuilder.Entity("CareerMate.Models.Entities.Industries.Industry", b =>
                {
                    b.HasOne("CareerMate.Models.Entities.Faculties.Faculty", "Faculty")
                        .WithMany("Industries")
                        .HasForeignKey("FacultyId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Faculty");
                });

            modelBuilder.Entity("CareerMate.Models.Entities.Interns.Intern", b =>
                {
                    b.HasOne("CareerMate.Models.Entities.Companies.Company", "Company")
                        .WithMany("Interns")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("CareerMate.Models.Entities.Internships.Internship", "Internship")
                        .WithMany("Interns")
                        .HasForeignKey("InternshipId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CareerMate.Models.Entities.Students.Student", "Student")
                        .WithOne("Intern")
                        .HasForeignKey("CareerMate.Models.Entities.Interns.Intern", "StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CareerMate.Models.Entities.Supervisors.Supervisor", "Supervisor")
                        .WithMany("Interns")
                        .HasForeignKey("SupervisorId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Company");

                    b.Navigation("Internship");

                    b.Navigation("Student");

                    b.Navigation("Supervisor");
                });

            modelBuilder.Entity("CareerMate.Models.Entities.InternshipInvites.InternshipInvite", b =>
                {
                    b.HasOne("CareerMate.Models.Entities.Internships.Internship", "Internship")
                        .WithMany("InternshipInvites")
                        .HasForeignKey("InternshipId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CareerMate.Models.Entities.Students.Student", "Student")
                        .WithMany("InternshipInvites")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Internship");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("CareerMate.Models.Entities.InternshipPosts.InternshipPost", b =>
                {
                    b.HasOne("CareerMate.Models.Entities.Companies.Company", "Company")
                        .WithMany("InternshipPosts")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("CareerMate.Models.Entities.Faculties.Faculty", "Faculty")
                        .WithMany("InternshipPosts")
                        .HasForeignKey("FacultyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CareerMate.Models.Entities.Internships.Internship", "Internship")
                        .WithOne("InternshipPost")
                        .HasForeignKey("CareerMate.Models.Entities.InternshipPosts.InternshipPost", "InternshipId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("CareerMate.Models.Entities.CoordinatorAssistants.CoordinatorAssistant", "PostedCoordinatorAssistant")
                        .WithMany("InternshipPosts")
                        .HasForeignKey("PostedCoordinatorAssistantId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("CareerMate.Models.Entities.Coordinators.Coordinator", "PostedCoordinator")
                        .WithMany("InternshipPosts")
                        .HasForeignKey("PostedCoordinatorId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("CareerMate.Models.Entities.Students.Student", "PostedStudent")
                        .WithMany("InternshipPosts")
                        .HasForeignKey("PostedStudentId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Company");

                    b.Navigation("Faculty");

                    b.Navigation("Internship");

                    b.Navigation("PostedCoordinator");

                    b.Navigation("PostedCoordinatorAssistant");

                    b.Navigation("PostedStudent");
                });

            modelBuilder.Entity("CareerMate.Models.Entities.Internships.Internship", b =>
                {
                    b.HasOne("CareerMate.Models.Entities.Companies.Company", "Company")
                        .WithMany("Internships")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CareerMate.Models.Entities.Faculties.Faculty", "Faculty")
                        .WithMany("Internships")
                        .HasForeignKey("FacultyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Company");

                    b.Navigation("Faculty");
                });

            modelBuilder.Entity("CareerMate.Models.Entities.Links.Contact", b =>
                {
                    b.HasOne("CareerMate.Models.Entities.Companies.Company", "Company")
                        .WithMany("Links")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("CareerMate.Models.Entities.Students.Student", "Student")
                        .WithMany("Links")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Company");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("CareerMate.Models.Entities.Pathways.Pathway", b =>
                {
                    b.HasOne("CareerMate.Models.Entities.Degrees.Degree", "Degree")
                        .WithMany("Pathways")
                        .HasForeignKey("DegreeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Degree");
                });

            modelBuilder.Entity("CareerMate.Models.Entities.Skills.Skill", b =>
                {
                    b.HasOne("CareerMate.Models.Entities.Companies.Company", "Company")
                        .WithMany("SkillsLookingFor")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("CareerMate.Models.Entities.Students.Student", "Student")
                        .WithMany("Skills")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Company");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("CareerMate.Models.Entities.StudentBatches.StudentBatch", b =>
                {
                    b.HasOne("CareerMate.Models.Entities.Faculties.Faculty", "Faculty")
                        .WithMany("StudentBatches")
                        .HasForeignKey("FacultyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Faculty");
                });

            modelBuilder.Entity("CareerMate.Models.Entities.Students.Student", b =>
                {
                    b.HasOne("CareerMate.Models.Entities.ApplicationUsers.ApplicationUser", "ApplicationUser")
                        .WithOne("Student")
                        .HasForeignKey("CareerMate.Models.Entities.Students.Student", "ApplicationUserId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("CareerMate.Models.Entities.StudentBatches.StudentBatch", "Batch")
                        .WithMany("Students")
                        .HasForeignKey("BatchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CareerMate.Models.Entities.Degrees.Degree", "Degree")
                        .WithMany("Students")
                        .HasForeignKey("DegreeId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("CareerMate.Models.Entities.Pathways.Pathway", "Pathway")
                        .WithMany("Students")
                        .HasForeignKey("PathwayId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.OwnsOne("CareerMate.Models.Entities.Students.CompanyFeedback", "CompanyFeedback", b1 =>
                        {
                            b1.Property<Guid>("StudentId")
                                .HasColumnType("uuid");

                            b1.Property<int?>("Level")
                                .HasColumnType("integer")
                                .HasColumnName("CompanyFeedbackLevel");

                            b1.Property<string>("Message")
                                .HasColumnType("text")
                                .HasColumnName("CompanyFeedbackMessage");

                            b1.HasKey("StudentId");

                            b1.ToTable("Student");

                            b1.WithOwner()
                                .HasForeignKey("StudentId");
                        });

                    b.OwnsOne("CareerMate.Models.Entities.Students.StudentMark", "Marks", b1 =>
                        {
                            b1.Property<Guid>("StudentId")
                                .HasColumnType("uuid");

                            b1.Property<int?>("DailyDiary")
                                .HasColumnType("integer")
                                .HasColumnName("DailyDiaryMarks");

                            b1.Property<int?>("Others")
                                .HasColumnType("integer")
                                .HasColumnName("OthersMarks");

                            b1.Property<int?>("Total")
                                .HasColumnType("integer")
                                .HasColumnName("TotalMarks");

                            b1.Property<int?>("Viva")
                                .HasColumnType("integer")
                                .HasColumnName("VivaMarks");

                            b1.HasKey("StudentId");

                            b1.ToTable("Student");

                            b1.WithOwner()
                                .HasForeignKey("StudentId");
                        });

                    b.Navigation("ApplicationUser");

                    b.Navigation("Batch");

                    b.Navigation("CompanyFeedback")
                        .IsRequired();

                    b.Navigation("Degree");

                    b.Navigation("Marks")
                        .IsRequired();

                    b.Navigation("Pathway");
                });

            modelBuilder.Entity("CareerMate.Models.Entities.Supervisors.Supervisor", b =>
                {
                    b.HasOne("CareerMate.Models.Entities.ApplicationUsers.ApplicationUser", "ApplicationUser")
                        .WithOne("Supervisor")
                        .HasForeignKey("CareerMate.Models.Entities.Supervisors.Supervisor", "ApplicationUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CareerMate.Models.Entities.Companies.Company", "Company")
                        .WithMany("Supervisors")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ApplicationUser");

                    b.Navigation("Company");
                });

            modelBuilder.Entity("CareerMate.Models.Entities.SysAdmins.SysAdmin", b =>
                {
                    b.HasOne("CareerMate.Models.Entities.ApplicationUsers.ApplicationUser", "ApplicationUser")
                        .WithOne("SysAdmin")
                        .HasForeignKey("CareerMate.Models.Entities.SysAdmins.SysAdmin", "ApplicationUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ApplicationUser");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.HasOne("CareerMate.Models.Entities.ApplicationUsers.ApplicationUserRoles", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.HasOne("CareerMate.Models.Entities.ApplicationUsers.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.HasOne("CareerMate.Models.Entities.ApplicationUsers.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.HasOne("CareerMate.Models.Entities.ApplicationUsers.ApplicationUserRoles", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CareerMate.Models.Entities.ApplicationUsers.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.HasOne("CareerMate.Models.Entities.ApplicationUsers.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CareerMate.Models.Entities.ApplicationUsers.ApplicationUser", b =>
                {
                    b.Navigation("Company");

                    b.Navigation("Coordinator");

                    b.Navigation("CoordinatorAssistant");

                    b.Navigation("Student");

                    b.Navigation("Supervisor");

                    b.Navigation("SysAdmin");
                });

            modelBuilder.Entity("CareerMate.Models.Entities.Companies.Company", b =>
                {
                    b.Navigation("Followers");

                    b.Navigation("Interns");

                    b.Navigation("InternshipPosts");

                    b.Navigation("Internships");

                    b.Navigation("Links");

                    b.Navigation("SkillsLookingFor");

                    b.Navigation("Supervisors");
                });

            modelBuilder.Entity("CareerMate.Models.Entities.CoordinatorAssistants.CoordinatorAssistant", b =>
                {
                    b.Navigation("InternshipPosts");
                });

            modelBuilder.Entity("CareerMate.Models.Entities.Coordinators.Coordinator", b =>
                {
                    b.Navigation("InternshipPosts");
                });

            modelBuilder.Entity("CareerMate.Models.Entities.DailyDiaries.DailyDiary", b =>
                {
                    b.Navigation("Records");
                });

            modelBuilder.Entity("CareerMate.Models.Entities.Degrees.Degree", b =>
                {
                    b.Navigation("Pathways");

                    b.Navigation("Students");
                });

            modelBuilder.Entity("CareerMate.Models.Entities.Faculties.Faculty", b =>
                {
                    b.Navigation("Companies");

                    b.Navigation("Coordinators");

                    b.Navigation("CoordinatorsAssistants");

                    b.Navigation("Degrees");

                    b.Navigation("Industries");

                    b.Navigation("InternshipPosts");

                    b.Navigation("Internships");

                    b.Navigation("StudentBatches");
                });

            modelBuilder.Entity("CareerMate.Models.Entities.Industries.Industry", b =>
                {
                    b.Navigation("Companies");
                });

            modelBuilder.Entity("CareerMate.Models.Entities.Interns.Intern", b =>
                {
                    b.Navigation("Diary");
                });

            modelBuilder.Entity("CareerMate.Models.Entities.InternshipPosts.InternshipPost", b =>
                {
                    b.Navigation("Applicants");
                });

            modelBuilder.Entity("CareerMate.Models.Entities.Internships.Internship", b =>
                {
                    b.Navigation("Interns");

                    b.Navigation("InternshipInvites");

                    b.Navigation("InternshipPost");
                });

            modelBuilder.Entity("CareerMate.Models.Entities.Pathways.Pathway", b =>
                {
                    b.Navigation("Students");
                });

            modelBuilder.Entity("CareerMate.Models.Entities.StudentBatches.StudentBatch", b =>
                {
                    b.Navigation("Students");
                });

            modelBuilder.Entity("CareerMate.Models.Entities.Students.Student", b =>
                {
                    b.Navigation("Applicants");

                    b.Navigation("Certification");

                    b.Navigation("CompanyFollowers");

                    b.Navigation("Diary");

                    b.Navigation("Experiences");

                    b.Navigation("Intern");

                    b.Navigation("InternshipInvites");

                    b.Navigation("InternshipPosts");

                    b.Navigation("LeaveRequests");

                    b.Navigation("Links");

                    b.Navigation("Skills");
                });

            modelBuilder.Entity("CareerMate.Models.Entities.Supervisors.Supervisor", b =>
                {
                    b.Navigation("Interns");
                });

            modelBuilder.Entity("CareerMate.Models.Entities.Universities.University", b =>
                {
                    b.Navigation("Faculties");
                });
#pragma warning restore 612, 618
        }
    }
}
